version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      DATABASE_URL: postgresql://user:password@localhost:5432/blog
      CONFIG_NAME: DevConfig
    ports:
      - "8080:5000"
    depends_on:
      - database

  database:
    image: postgres:12.7-alpine
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: roover
      POSTGRES_PASSWORD: password
    volumes:
      - ${HOME}/dbs/flask-lesson/pgdata_dev:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
