"""empty message

Revision ID: 025b1fd4443e
Revises: ee7b14582cc1
Create Date: 2023-03-23 00:48:10.688031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025b1fd4443e'
down_revision = 'ee7b14582cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
