"""empty message

Revision ID: 0d7cbc9eb9a1
Revises: 5dc57bbb7c3e
Create Date: 2023-03-26 17:12:16.222537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7cbc9eb9a1'
down_revision = '5dc57bbb7c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('articles_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('articles_ibfk_1', 'users', ['author_id'], ['id'])
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
