"""empty message

Revision ID: 882cd571fe04
Revises: 0d7cbc9eb9a1
Create Date: 2023-03-29 14:38:41.568031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882cd571fe04'
down_revision = '0d7cbc9eb9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    # ### end Alembic commands ###
